code-projet/app-pwa/config/routes.rb
Rails.application.routes.draw do
  resources :order_products
  resources :orders
  resources :bakers
  resources :bakery_photos
  resources :bakery_products
  resources :products
  resources :bakeries
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  resources :users
  get 'admin/index'
  get 'admin/users'
  get 'appli/map'
  get 'appli/panier'
  get 'appli/commandes'
  get 'appli/bakery'
  get 'welcome/registration'
  root 'welcome#index'
end

code-projet/app-pwa/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

code-projet/app-pwa/app/models/baker.rb
class Baker < ApplicationRecord
  belongs_to :bakery
  belongs_to :user
end

code-projet/app-pwa/app/models/bakery.rb
class Bakery < ApplicationRecord
end

code-projet/app-pwa/app/models/bakery_photo.rb
class BakeryPhoto < ApplicationRecord
  belongs_to :bakery
end

code-projet/app-pwa/app/models/bakery_product.rb
class BakeryProduct < ApplicationRecord
  belongs_to :bakery
  belongs_to :product
end

code-projet/app-pwa/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :bakery
end

code-projet/app-pwa/app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :bakery_product
end

code-projet/app-pwa/app/models/product.rb
class Product < ApplicationRecord
end

code-projet/app-pwa/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  def admin?
    is_admin
  end
end

code-projet/app-pwa/app/controllers/admin_controller.rb
# frozen_string_literal: true

# Admin controller
class AdminController < ApplicationController
  layout 'admin'

  def index
    if current_user.admin?
    else
      redirect_to :map_index
    end
  end

  def users
    @users = User.all
  end
end

code-projet/app-pwa/app/controllers/appli_controller.rb
class AppliController < ApplicationController
  before_action :authenticate_user!

  def map
    @google_api_key = 'AIzaSyB5KXgwu69_newK7Q5ZSzioRF4TVOWCf1k'
    @map_zoom = 16
    if params['search']
      result = Geocoder.search(params['search'])
      @map_center = result.first.coordinates
      @bakeries = Bakery.where(city: params['search'])
      @user_loc = ''
    elsif !current_user.postal_code.nil? && !current_user.street.nil? && !current_user.city.nil? && !current_user.country.nil?
      address_user = current_user.street + ', ' + current_user.postal_code + ' ' + current_user.city + ', ' + current_user.country
      result = Geocoder.search(address_user)
      @map_center = result.first.coordinates
      @bakeries = Bakery.where(city: current_user.city)
      @user_loc = address_user
    else
      @map_center = [50.6305089, 3.0706414]
      city = Geocoder.search([50.6305089, 3.0706414])
      @bakeries = Bakery.where(city: city.city)
      @user_loc = ''
    end
  end

  def profil;
  end

  def panier;
  end

  def commandes;
  end

  def bakery;
    @bakery = Bakery.where(id: 1).first
    @products = BakeryProduct.where(bakery_id: @bakery.id)
  end

end

code-projet/app-pwa/app/controllers/bakers_controller.rb
class BakersController < ApplicationController
  layout 'admin'
  before_action :set_baker, only: [:show, :edit, :update, :destroy]

  # GET /bakers
  # GET /bakers.json
  def index
    if current_user.admin?
      @bakers = Baker.all
    else
      redirect_to :map_index
    end

  end

  # GET /bakers/1
  # GET /bakers/1.json
  def show
    if current_user.admin?
    else
      redirect_to :map_index
    end
  end

  # GET /bakers/new
  def new
    if current_user.admin?
      @baker = Baker.new
    else
      redirect_to :map_index
    end

  end

  # GET /bakers/1/edit
  def edit
    if current_user.admin?
    else
      redirect_to :map_index
    end
  end

  # POST /bakers
  # POST /bakers.json
  def create
    if current_user.admin?
      @baker = Baker.new(baker_params)

      respond_to do |format|
        if @baker.save
          format.html { redirect_to @baker, notice: 'Baker was successfully created.' }
          format.json { render :show, status: :created, location: @baker }
        else
          format.html { render :new }
          format.json { render json: @baker.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :map_index
    end

  end

  # PATCH/PUT /bakers/1
  # PATCH/PUT /bakers/1.json
  def update
    if current_user.admin?
      respond_to do |format|
        if @baker.update(baker_params)
          format.html { redirect_to @baker, notice: 'Baker was successfully updated.' }
          format.json { render :show, status: :ok, location: @baker }
        else
          format.html { render :edit }
          format.json { render json: @baker.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :map_index
    end

  end

  # DELETE /bakers/1
  # DELETE /bakers/1.json
  def destroy
    if current_user.admin?
      @baker.destroy
      respond_to do |format|
        format.html { redirect_to bakers_url, notice: 'Baker was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to :map_index
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baker
      @baker = Baker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baker_params
      params.require(:baker).permit(:bakery_id, :user_id)
    end
end

code-projet/app-pwa/app/helpers/admin_helper.rb
module AdminHelper
end

code-projet/app-pwa/app/helpers/application_helper.rb
module ApplicationHelper

  def resource
    @resource ||= User.new
  end

  def resource_name
    :user
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

code-projet/app-pwa/app/helpers/bakeries_helper.rb
module BakeriesHelper
end

code-projet/app-pwa/app/helpers/bakers_helper.rb
module BakersHelper
end

code-projet/app-pwa/app/helpers/bakery_photos_helper.rb
module BakeryPhotosHelper
end

code-projet/app-pwa/app/helpers/map_helper.rb
module MapHelper
end

code-projet/app-pwa/app/helpers/orders_helper.rb
module OrdersHelper
end

code-projet/app-pwa/app/helpers/products_helper.rb
module ProductsHelper
end

code-projet/app-pwa/app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

code-projet/app-pwa/app/views/admin/users.html.erb
<h1>Users</h1>

<table class="table">
  <thead>
  <tr>
    <th>Role</th>
    <th>Email</th>
    <th>Prenom</th>
    <th>Nom</th>
    <th>Créé le</th>
    <th>Adresse</th>
    <th>Code postal</th>
    <th>Ville</th>
    <th>Pays</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <% if user.is_admin? %>
        <td>Administrateur</td>
      <% else %>
        <td>Utilisateur</td>
      <% end %>
      <td><%= user.email %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.created_at %></td>
      <td><%= user.street %></td>
      <td><%= user.postal_code %></td>
      <td><%= user.city %></td>
      <td><%= user.country %></td>

      <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

code-projet/app-pwa/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>La carte du pain</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= stylesheet_link_tag 'admin' %>
  <%= stylesheet_link_tag 'util' %>
  <%= stylesheet_link_tag 'fontawesome' %>

</head>

<body>

<header>
  <div class=topbar>
    <h1><%= link_to 'Administration', admin_index_path, style: 'color: #ffffff' %></h1>
    <section>
      <div class="container-login100-form-btn">
        <%= link_to 'Deconnexion', destroy_user_session_path, method: :delete, :class => "login100-form-btn" %>
      </div>
    </section>
  </div>
</header>
  <nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="mt">
        <%= link_to 'Users', admin_users_path, style: 'color: #ffffff' %>
      </li>
      <li>
        <%= link_to 'Bakeries', bakeries_path, style: 'color: #ffffff' %>
      </li>
      <li>
        <%= link_to 'BakeryPhotos', bakery_photos_path, style: 'color: #ffffff' %>
      </li>
      <li>
        <%= link_to 'Bakers', bakers_path, style: 'color: #ffffff' %>
      </li>
      <li>
        <%= link_to 'Products', products_path, style: 'color: #ffffff' %>
      </li>
      <li>
        <%= link_to 'BakeryProducts', bakery_products_path, style: 'color: #ffffff' %>
      </li>
      <li>
        <%= link_to 'Orders', orders_path, style: 'color: #ffffff' %>
      </li>
      <li>
        <%= link_to 'OrderProducts', order_products_path, style: 'color: #ffffff' %>
      </li>
    </ul>
  </nav>
  <section>
    <div class='admin-body'>
      <%= yield %>
    </div>
  </section>
</body>
</html>

code-projet/app-pwa/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>La carte du pain</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>

  <%= stylesheet_link_tag 'appli' %>
  <%= stylesheet_link_tag 'util' %>
  <%= stylesheet_link_tag 'fontawesome' %>
  <%= stylesheet_link_tag 'searchbar-menu' %>
</head>

<body>
<header>
  <div class=topbar>
    <h1><%= link_to 'La carte du pain', appli_map_path, style: 'color: #ffffff' %></h1>
    <section>
      <div class="container-login100-form-btn">
        <%= link_to 'Boulangerie 1', appli_bakery_path, :class => "login100-form-btn" %>
        <%= link_to 'Panier', appli_panier_path, :class => "login100-form-btn" %>
        <%= link_to 'Deconnexion', destroy_user_session_path, method: :delete, :class => "login100-form-btn" %>
      </div>
    </section>
  </div>
</header>
<section>
  <div class="form-et-map">
    <%= yield %>
  </div>
</section>
</body>
</html>

code-projet/app-pwa/app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>La carte du pain</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= stylesheet_link_tag 'background-welcome' %>
  <%= stylesheet_link_tag 'welcome' %>
  <%= stylesheet_link_tag 'util' %>
  <%= stylesheet_link_tag 'fontawesome' %>
</head>

<body>

<%= yield %>

</body>
</html>