code-projet/app-pwa/config/routes.rb
Rails.application.routes.draw do
  resources :order_products
  resources :orders
  resources :bakers
  resources :bakery_photos
  resources :bakery_products
  resources :products
  resources :bakeries
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  resources :users
  get 'admin/index'
  get 'admin/users'
  get 'appli/map'
  get 'appli/panier'
  get 'appli/commandes'
  get 'appli/bakery'
  get 'welcome/registration'
  root 'welcome#index'
end

code-projet/app-pwa/app/models/baker.rb
class Baker < ApplicationRecord
  belongs_to :bakery
  belongs_to :user
end

code-projet/app-pwa/app/controllers/bakers_controller.rb
class BakersController < ApplicationController
  layout 'admin'
  before_action :set_baker, only: [:show, :edit, :update, :destroy]

  # GET /bakers
  # GET /bakers.json
  def index
    if current_user.admin?
      @bakers = Baker.all
    else
      redirect_to :map_index
    end

  end

  # GET /bakers/1
  # GET /bakers/1.json
  def show
    if current_user.admin?
    else
      redirect_to :map_index
    end
  end

  # GET /bakers/new
  def new
    if current_user.admin?
      @baker = Baker.new
    else
      redirect_to :map_index
    end

  end

  # GET /bakers/1/edit
  def edit
    if current_user.admin?
    else
      redirect_to :map_index
    end
  end

  # POST /bakers
  # POST /bakers.json
  def create
    if current_user.admin?
      @baker = Baker.new(baker_params)

      respond_to do |format|
        if @baker.save
          format.html { redirect_to @baker, notice: 'Baker was successfully created.' }
          format.json { render :show, status: :created, location: @baker }
        else
          format.html { render :new }
          format.json { render json: @baker.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :map_index
    end

  end

  # PATCH/PUT /bakers/1
  # PATCH/PUT /bakers/1.json
  def update
    if current_user.admin?
      respond_to do |format|
        if @baker.update(baker_params)
          format.html { redirect_to @baker, notice: 'Baker was successfully updated.' }
          format.json { render :show, status: :ok, location: @baker }
        else
          format.html { render :edit }
          format.json { render json: @baker.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :map_index
    end

  end

  # DELETE /bakers/1
  # DELETE /bakers/1.json
  def destroy
    if current_user.admin?
      @baker.destroy
      respond_to do |format|
        format.html { redirect_to bakers_url, notice: 'Baker was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to :map_index
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baker
      @baker = Baker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baker_params
      params.require(:baker).permit(:bakery_id, :user_id)
    end
end

code-projet/app-pwa/app/helpers/bakers_helper.rb
module BakersHelper
end

code-projet/app-pwa/app/views/bakers/_form.html.erb
<%= form_with(model: baker, local: true) do |form| %>
  <% if baker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baker.errors.count, "error") %> prohibited this baker from being saved:</h2>

      <ul>
      <% baker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bakery_id %>
    <%= form.text_field :bakery_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

code-projet/app-pwa/app/views/bakers/edit.html.erb
<h1>Editing Baker</h1>

<%= render 'form', baker: @baker %>

<%= link_to 'Show', @baker %> |
<%= link_to 'Back', bakers_path %>

code-projet/app-pwa/app/views/bakers/index.html.erb
<h1>Bakers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Bakery</th>
      <th>User</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @bakers.each do |baker| %>
      <tr>
        <td><%= baker.bakery %></td>
        <td><%= baker.user %></td>
        <td><%= link_to 'Show', baker %></td>
        <td><%= link_to 'Edit', edit_baker_path(baker) %></td>
        <td><%= link_to 'Destroy', baker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baker', new_baker_path %>

code-projet/app-pwa/app/views/bakers/new.html.erb
<h1>New Baker</h1>

<%= render 'form', baker: @baker %>

<%= link_to 'Back', bakers_path %>

code-projet/app-pwa/app/views/bakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bakery:</strong>
  <%= @baker.bakery %>
</p>

<p>
  <strong>User:</strong>
  <%= @baker.user %>
</p>

<%= link_to 'Edit', edit_baker_path(@baker) %> |
<%= link_to 'Back', bakers_path %>