code-projet/app-pwa/config/routes.rb
Rails.application.routes.draw do
  resources :order_products
  resources :orders
  resources :bakers
  resources :bakery_photos
  resources :bakery_products
  resources :products
  resources :bakeries
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  resources :users
  get 'admin/index'
  get 'admin/users'
  get 'appli/map'
  get 'appli/panier'
  get 'appli/commandes'
  get 'appli/bakery'
  get 'welcome/registration'
  root 'welcome#index'
end

code-projet/app-pwa/app/models/bakery_photo.rb
class BakeryPhoto < ApplicationRecord
  belongs_to :bakery
end

code-projet/app-pwa/app/controllers/bakery_photos_controller.rb
class BakeryPhotosController < ApplicationController
  layout 'admin'
  before_action :set_bakery_photo, only: [:show, :edit, :update, :destroy]

  # GET /bakery_photos
  # GET /bakery_photos.json
  def index
    if current_user.admin?
      @bakery_photos = BakeryPhoto.all
    else
      redirect_to :map_index
    end
  end

  # GET /bakery_photos/1
  # GET /bakery_photos/1.json
  def show
    if current_user.admin?
    else
      redirect_to :map_index
    end
  end

  # GET /bakery_photos/new
  def new
    if current_user.admin?
      @bakery_photo = BakeryPhoto.new
    else
      redirect_to :map_index
    end
  end

  # GET /bakery_photos/1/edit
  def edit
    if current_user.admin?
    else
      redirect_to :map_index
    end
  end

  # POST /bakery_photos
  # POST /bakery_photos.json
  def create
    if current_user.admin?
      @bakery_photo = BakeryPhoto.new(bakery_photo_params)

      respond_to do |format|
        if @bakery_photo.save
          format.html { redirect_to @bakery_photo, notice: 'Bakery photo was successfully created.' }
          format.json { render :show, status: :created, location: @bakery_photo }
        else
          format.html { render :new }
          format.json { render json: @bakery_photo.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :map_index
    end
  end

  # PATCH/PUT /bakery_photos/1
  # PATCH/PUT /bakery_photos/1.json
  def update
    if current_user.admin?
      respond_to do |format|
        if @bakery_photo.update(bakery_photo_params)
          format.html { redirect_to @bakery_photo, notice: 'Bakery photo was successfully updated.' }
          format.json { render :show, status: :ok, location: @bakery_photo }
        else
          format.html { render :edit }
          format.json { render json: @bakery_photo.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :map_index
    end
  end

  # DELETE /bakery_photos/1
  # DELETE /bakery_photos/1.json
  def destroy
    if current_user.admin?
      @bakery_photo.destroy
      respond_to do |format|
        format.html { redirect_to bakery_photos_url, notice: 'Bakery photo was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to :map_index
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bakery_photo
      @bakery_photo = BakeryPhoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bakery_photo_params
      params.require(:bakery_photo).permit(:bakery_id, :photo)
    end
end

code-projet/app-pwa/app/helpers/bakery_photos_helper.rb
module BakeryPhotosHelper
end

code-projet/app-pwa/app/views/bakery_photos/_form.html.erb
<%= form_with(model: bakery_photo, local: true) do |form| %>
  <% if bakery_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bakery_photo.errors.count, "error") %> prohibited this bakery_photo from being saved:</h2>

      <ul>
      <% bakery_photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bakery_id %>
    <%= form.text_field :bakery_id %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

code-projet/app-pwa/app/views/bakery_photos/edit.html.erb
<h1>Editing Bakery Photo</h1>

<%= render 'form', bakery_photo: @bakery_photo %>

<%= link_to 'Show', @bakery_photo %> |
<%= link_to 'Back', bakery_photos_path %>

code-projet/app-pwa/app/views/bakery_photos/index.html.erb
<h1>Bakery Photos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Bakery</th>
      <th>Photo</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @bakery_photos.each do |bakery_photo| %>
      <tr>
        <td><%= bakery_photo.bakery %></td>
        <td><%= bakery_photo.photo %></td>
        <td><%= link_to 'Show', bakery_photo %></td>
        <td><%= link_to 'Edit', edit_bakery_photo_path(bakery_photo) %></td>
        <td><%= link_to 'Destroy', bakery_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bakery Photo', new_bakery_photo_path %>

code-projet/app-pwa/app/views/bakery_photos/new.html.erb
<h1>New Bakery Photo</h1>

<%= render 'form', bakery_photo: @bakery_photo %>

<%= link_to 'Back', bakery_photos_path %>

code-projet/app-pwa/app/views/bakery_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bakery:</strong>
  <%= @bakery_photo.bakery %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @bakery_photo.photo %>
</p>

<%= link_to 'Edit', edit_bakery_photo_path(@bakery_photo) %> |
<%= link_to 'Back', bakery_photos_path %>