code-projet/app-pwa/config/routes.rb
Rails.application.routes.draw do
  resources :order_products
  resources :orders
  resources :bakers
  resources :bakery_photos
  resources :bakery_products
  resources :products
  resources :bakeries
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  resources :users
  get 'admin/index'
  get 'admin/users'
  get 'appli/map'
  get 'appli/panier'
  get 'appli/commandes'
  get 'appli/bakery'
  get 'welcome/registration'
  root 'welcome#index'
end

code-projet/app-pwa/app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :bakery_product
end

code-projet/app-pwa/app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  layout 'admin'
  before_action :set_order_product, only: [:show, :edit, :update, :destroy]

  # GET /order_products
  # GET /order_products.json
  def index
    if current_user.admin?
      @order_products = OrderProduct.all
    else
      redirect_to :map_index
    end
  end

  # GET /order_products/1
  # GET /order_products/1.json
  def show
    if current_user.admin?

    else
      redirect_to :map_index
    end
  end

  # GET /order_products/new
  def new
    if current_user.admin?
      @order_product = OrderProduct.new
    else
      redirect_to :map_index
    end
  end

  # GET /order_products/1/edit
  def edit
    if current_user.admin?

    else
      redirect_to :map_index
    end
  end

  # POST /order_products
  # POST /order_products.json
  def create
    if current_user.admin?
      @order_product = OrderProduct.new(order_product_params)

      respond_to do |format|
        if @order_product.save
          format.html { redirect_to @order_product, notice: 'Order product was successfully created.' }
          format.json { render :show, status: :created, location: @order_product }
        else
          format.html { render :new }
          format.json { render json: @order_product.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :map_index
    end
  end

  # PATCH/PUT /order_products/1
  # PATCH/PUT /order_products/1.json
  def update
    if current_user.admin?
      respond_to do |format|
        if @order_product.update(order_product_params)
          format.html { redirect_to @order_product, notice: 'Order product was successfully updated.' }
          format.json { render :show, status: :ok, location: @order_product }
        else
          format.html { render :edit }
          format.json { render json: @order_product.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :map_index
    end
  end

  # DELETE /order_products/1
  # DELETE /order_products/1.json
  def destroy
    if current_user.admin?
      @order_product.destroy
      respond_to do |format|
        format.html { redirect_to order_products_url, notice: 'Order product was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to :map_index
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_product
      @order_product = OrderProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_product_params
      params.require(:order_product).permit(:order_id, :bakery_product_id, :quantity)
    end
end

code-projet/app-pwa/app/helpers/order_products_helper.rb
module OrderProductsHelper
end

code-projet/app-pwa/app/views/order_products/_form.html.erb
<%= form_with(model: order_product, local: true) do |form| %>
  <% if order_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_product.errors.count, "error") %> prohibited this order_product from being saved:</h2>

      <ul>
      <% order_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :bakery_product_id %>
    <%= form.text_field :bakery_product_id %>
  </div>

  <div class="field">
    <%= form.label :quantity_id %>
    <%= form.text_field :quantity_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

code-projet/app-pwa/app/views/order_products/edit.html.erb
<h1>Editing Order Product</h1>

<%= render 'form', order_product: @order_product %>

<%= link_to 'Show', @order_product %> |
<%= link_to 'Back', order_products_path %>

code-projet/app-pwa/app/views/order_products/index.html.erb
<h1>Order Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Order</th>
      <th>Bakery product</th>
      <th>Quantity</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @order_products.each do |order_product| %>
      <tr>
        <td><%= order_product.order %></td>
        <td><%= order_product.bakery_product %></td>
        <td><%= order_product.quantity %></td>
        <td><%= link_to 'Show', order_product %></td>
        <td><%= link_to 'Edit', edit_order_product_path(order_product) %></td>
        <td><%= link_to 'Destroy', order_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Product', new_order_product_path %>

code-projet/app-pwa/app/views/order_products/new.html.erb
<h1>New Order Product</h1>

<%= render 'form', order_product: @order_product %>

<%= link_to 'Back', order_products_path %>

code-projet/app-pwa/app/views/order_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_product.order %>
</p>

<p>
  <strong>Bakery product:</strong>
  <%= @order_product.bakery_product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_product.quantity %>
</p>

<%= link_to 'Edit', edit_order_product_path(@order_product) %> |
<%= link_to 'Back', order_products_path %>